### ISSUE TITLE
chronyd 2.4.1 "Fatal error : Possible infinite loop in scheduling"

### ISSUE THREAD

**Issue by vollkommenheit** [mlichvar/chrony#1] opened 2016-12-09 18:48 UTC
On my openwrt router, chronyd 2.4.1 would crash with "Fatal error : Possible infinite loop in scheduling". It appears to be related to the number of time servers/pools configured in chrony.conf, even when chrony is started manually. 

There's no specific number of time servers/pools that would cause this crash, although there's a range in my limited testing: 9-13, while 8-12 were ok. Initially, it crashed with 9 servers configured, but came up with 8 servers configured. When 4 pools were substituted in for 4 of the servers, it still came up fine. Adding 2 more servers, one at a time, making it a total of 6 server + 4 pools, did not cause crash on restarts. When all the existing servers/pools got replaced by 20 new time servers, it crashed again on restart. Reducing the number of servers from 20 to 10, it came up fine again. Gradually increasing the number to 12, it kept coming up fine. But when 13 servers were configured, it started crashing again.

All the servers/pools are configured with the "iburst" option, in case it matters.

I see there was an old bug (circa 2011) filed and fixed for something similar: https://bugzilla.redhat.com/show_bug.cgi?format=multiple&id=736879

It seems what I'm encountering might also be due to DNS lookup in some way, because I'm running "unbound" as a validating and caching resolver with DNSSEC, which could slow down the initial lookups. However, I would think subsequent chronyd restarts would be problem-free, since by then most (if not all) lookups are cached (response times of 0-1 ms, per "dig"). So subsequent crashes upon restart of chrony, with the same [large] number of time servers, cannot be due to name resolutions.

uname -a
Linux localhost 4.4.14 #1 Tue Nov 22 10:36:02 UTC 2016 mips GNU/Linux

chronyd -v
chronyd (chrony) version 2.4.1 (+CMDMON +NTP +REFCLOCK -RTC +PRIVDROP -SCFILTER -SECHASH -ASYNCDNS +IPV6 -DEBUG)

**Comment by mlichvar** [comment] 2016-12-12 08:19
Thanks for the report. I'll see if I can reproduce it. The problem is mostly likely due to synchronous name resolving (-ASYNCDNS). Was it disabled intentionally? FWIW, the OpenWrt/LEDE chrony package is compiled with +ASYNCDNS.

**Comment by vollkommenheit** [comment] 2016-12-12 15:29
Thank you for your reply. I have the trunk version of chrony (from https://downloads.openwrt.org/snapshots/trunk/ar71xx/generic/packages/packages/chrony_2.4.1-1_ar71xx.ipk), which appears to have -ASYNCDNS compiled in. I have removed it and reinstalled. It still shows the same compile options:

opkg update
/etc/init.d/chronyd stop
opkg remove chrony
opkg list-installed |grep chron
opkg install chrony
/etc/init.d/chronyd enable
/etc/init.d/chronyd start
chronyd -v
chronyd (chrony) version 2.4.1 (+CMDMON +NTP +REFCLOCK -RTC +PRIVDROP -SCFILTER -SECHASH -ASYNCDNS +IPV6 -DEBUG)

**Comment by mlichvar** [comment] 2016-12-13 12:22
The crash with synchronous resolving should be now fixed with commit 0c9a19ded56ed893aab02e1f62ca259236bdf6e0.

I'll look into the issue with disabled ASYNCDNS in OpenWrt builds. It's supposed to be enabled. The RTC support is intentionally disabled as it's not very useful on routers. Most of them don't have an RTC and if they do, they typically have a permanent network connection and are not turned off for longer periods of time.

**Closed by mlichvar** 2016-12-13 12:22 UTC
